### ISSUE TITLE
Починить баг с зимним пальто для заключённых

### ISSUE THREAD

**Issue by kzhanik** [starfort-station/station-14#303]
## Баг

Есть зимнее пальто для заключённых, у которого отвалился спрайт. Нужно понять почему он отвалился, а после убрать причину отвала. Если дело в спрайте - заказать ещё спрайт.

Вот отчёт об ошибке кому надо:

```
Run dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
Unhandled exception. NUnit.Framework.AssertionException: CLIENT: 14,405s [ERRO] go.comp.sprite: Unable to load RSI '/Textures/Starfort/Clothing/OuterClothing/WinterCoats/prisonner-coat.rsi'. Exception: 
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail(String message)
   at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolTestLogHandler.cs:line [6](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:7)0
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 113
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 124
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 124
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 124
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, Exception exception, String message, Object[] args) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line [7](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:8)[8](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:9)
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line [9](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:10)0
   at Robust.Client.GameObjects.SpriteComponent.Robust.Shared.Serialization.ISerializationHooks.AfterDeserialization() in /home/runner/work/station-[14](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:15)/station-14/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 364
   at Robust.Shared.Prototypes.PrototypeManager.ResolveResults() in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.cs:line 451
   at Robust.Client.Prototypes.ClientPrototypeManager.LoadDefaultPrototypes(Dictionary`2 changed) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Client/Prototypes/ClientPrototypeManager.cs:line 49
   at Robust.Client.GameController.StartupContinue(DisplayMode displayMode) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line [16](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:17)9
   at Robust.UnitTesting.RobustIntegrationTest.ClientIntegrationInstance.Init() in /home/runner/work/station-14/station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 854
   at Robust.UnitTesting.RobustIntegrationTest.ClientIntegrationInstance.ThreadMain() in /home/runner/work/station-14/station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 752
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in /home/runner/work/station-14/station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 395
   at Content.IntegrationTests.PoolManager.GenerateClient(PoolSettings poolSettings, TextWriter testOut) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolManager.cs:line 232
   at Content.IntegrationTests.PoolManager.CreateServerClientPair(PoolSettings poolSettings, TextWriter testOut) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolManager.cs:line 527
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolManager.cs:line 300
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolManager.cs:line 340
   at Content.IntegrationTests.PoolManager.GetServerClient(PoolSettings poolSettings) in /home/runner/work/station-14/station-14/Content.IntegrationTests/PoolManager.cs:line 274
   at Content.YAMLLinter.Program.ValidateServer() in /home/runner/work/station-14/station-14/Content.YAMLLinter/Program.cs:line 61
   at Content.YAMLLinter.Program.RunValidation() in /home/runner/work/station-14/station-14/Content.YAMLLinter/Program.cs:line 89
   at Content.YAMLLinter.Program.Main(String[] _) in /home/runner/work/station-14/station-14/Content.YAMLLinter/Program.cs:line [21](https://github.com/starfort-station/station-14/actions/runs/5715554140/job/15485133998?pr=302#step:9:22)
   at Content.YAMLLinter.Program.<Main>(String[] _)
```

**Comment by 778b** [comment]
потому что директория криво написана

**Comment by Drayff** [comment]
Неправильный регистр '/Textures/Starfort/Clothing/OuterClothing/**WinterCoats**/prisonner-coat.rsi'
В \Resources\Prototypes\Starfort\Entities\Clothing\OuterClothing\wintercoats.yml нужно поменять WinterCoats на Wintercoats
